services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./postgres/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    networks:
      - pharma-db-network
  django:
    image: tyamadabiodataeng/pharma-dbms-django-dev
    container_name: django
    build:
      context: ./app
      dockerfile: ../dockerfiles/django/Dockerfile
      args:
        DIR_WORK: "/usr/src"
        ENV_YAML: "environment.dev.yaml"
        VENV: "dbms-django-dev"
    command: mamba run --name dbms-django-dev gunicorn config.wsgi.prod:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/usr/src
    expose:
      - "8000"
    env_file:
      - ./app/config/.env.dev
    depends_on:
      - postgres
    networks:
      - pharma-db-network
  nginx:
    image: tyamadabiodataeng/pharma-dbms-nginx
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ../dockerfiles/nginx/Dockerfile
    volumes:
      - ./app/static:/usr/src/static
      - ./app/media:/usr/src/media
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - pharma-db-network
  jupyter:
    build: 
      context: ./notebooks
      dockerfile: ../dockerfiles/jupyter/Dockerfile
      args:
        DIR_WORK: "/usr/src"
        ENV_YAML: "environment.yaml"
        VENV: "dbms-jupyter"
    image: tyamadabiodataeng/pharma-dbms-jupyter
    container_name: jupyter
    command: mamba run --name dbms-jupyter jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - ./notebooks:/usr/src
    tty: true
    stdin_open: true
    depends_on:
      - nginx
    networks:
      - pharma-db-network

networks:
  pharma-db-network:
    driver: bridge

volumes:
  postgres_data:
