name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: ci
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        python-version: ${{ matrix.python-version }}
        environment-file: app/environment.dev.yaml
        activate-environment: dbms-django-dev
    - name: Run Tests
      working-directory: app
      env:
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_USER: ${{ secrets.POSTGRES_USER }}
        DATABASE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_SCHEMA: ${{ secrets.DATABASE_SCHEMA }}
      run: |
        conda run --name dbms-django-dev python manage.py makemigrations accounts --dry-run
        conda run --name dbms-django-dev python manage.py migrate
        conda run --name dbms-django-dev pytest
